### ISSUE TITLE
[Compat] - Importer and Exporter do not work with "Reborn Storage" wireless grids

### ISSUE THREAD

**Issue by ArsiTheFox** [starforcraft/RS-Insert-Export-Upgrade#1]
The importer and exporter upgrades do not function with the Super Wireless Grid from "Reborn Storage". The upgrades fit in the device but they don't function at all

Instance: ATM9 1.20.1
Pack Version: All the Mods 9-0.2.37
Forge: 47.2.19

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/rs-insert-export-upgrade/files/5101865
